export const hasValidClerkKey =
  !!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY &&
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY !== 'YOUR_PUBLISHABLE_KEY' &&
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY.startsWith('pk_') &&
  !/REPLACE_ME|YOUR_PUBLISHABLE_KEY|YOUR_KEY|PLACEHOLDER/i.test(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

export const clerkAppearance = {
  variables: {
    colorPrimary: '#EA580C',
    colorBackground: '#18181b',
    colorInputBackground: '#18181b',
    colorInputText: '#f4f4f5',
    colorText: '#f4f4f5',
    colorTextSecondary: '#a1a1aa',
    colorTextOnPrimaryBackground: '#ffffff',
    colorNeutral: '#a1a1aa',
    colorDanger: '#f87171',
    colorSuccess: '#4ade80',
    colorWarning: '#fbbf24',
    borderRadius: '0.5rem',
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif',
    fontSize: '14px',
    spacingUnit: '4px',
  },
  layout: {
    socialButtonsPlacement: 'bottom',
    socialButtonsVariant: 'blockButton',
  },
  elements: {
    rootBox: { width: '100%' },
    card: {
      background: 'transparent',
      boxShadow: 'none',
      border: 'none',
      padding: 0,
      width: '100%',
    },
    headerTitle: {
      color: '#f4f4f5',
      fontWeight: '700',
      fontSize: '1.25rem',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    headerSubtitle: {
      color: '#a1a1aa',
      fontSize: '0.9rem',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      marginTop: '4px',
    },
    socialButtonsBlockButton: {
      background: '#27272a',
      border: '1.5px solid #3f3f46',
      borderRadius: '0.5rem',
      color: '#e4e4e7',
      fontWeight: '500',
      transition: 'background 0.15s, border-color 0.15s',
      minHeight: '48px',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    socialButtonsBlockButtonText: {
      color: '#e4e4e7',
      fontWeight: '500',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    dividerLine: { background: '#3f3f46' },
    dividerText: {
      color: '#71717a',
      fontSize: '0.75rem',
      background: '#0a0a0a',
      padding: '0 0.5rem',
      fontFamily: 'IBM Plex Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
    },
    formFieldLabel: {
      color: '#e4e4e7',
      fontSize: '0.82rem',
      fontWeight: '600',
      marginBottom: '4px',
      display: 'block',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    formFieldInput: {
      background: '#27272a',
      border: '1.5px solid #52525b',
      borderRadius: '0.5rem',
      color: '#f4f4f5',
      fontSize: '0.9rem',
      padding: '12px 14px',
      width: '100%',
      minHeight: '48px',
      outline: 'none',
      transition: 'border-color 0.15s, box-shadow 0.15s',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    formFieldInputShowPasswordButton: {
      color: '#a1a1aa',
    },
    formButtonPrimary: {
      background: '#EA580C',
      borderRadius: '0.5rem',
      color: '#ffffff',
      fontWeight: '700',
      fontSize: '0.85rem',
      padding: '12px 16px',
      width: '100%',
      minHeight: '48px',
      border: 'none',
      cursor: 'pointer',
      transition: 'background 0.15s, transform 0.1s',
      fontFamily: 'IBM Plex Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
    },
    footerActionLink: {
      color: '#f97316',
      fontWeight: '600',
      textDecoration: 'none',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    footerActionText: {
      color: '#a1a1aa',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    },
    footerAction: {
      borderTop: '1px solid #27272a',
      paddingTop: '1rem',
      marginTop: '1rem',
    },
    identityPreviewText: { color: '#d4d4d8' },
    identityPreviewEditButton: { color: '#f97316' },
    formFieldSuccessText: { color: '#4ade80', fontSize: '0.75rem' },
    formFieldErrorText: { color: '#f87171', fontSize: '0.75rem', marginTop: '4px' },
    alert: {
      background: 'rgba(127,29,29,0.3)',
      border: '1px solid rgba(239,68,68,0.4)',
      borderRadius: '0.5rem',
      padding: '12px',
    },
    alertText: { color: '#fca5a5', fontSize: '0.875rem' },
    formResendCodeLink: { color: '#f97316', fontSize: '0.85rem' },
    otpCodeFieldInputs: {
      gap: '0.5rem',
    },
    otpCodeFieldInput: {
      background: '#27272a',
      border: '2px solid #52525b',
      borderRadius: '0.625rem',
      color: '#f4f4f5',
      textAlign: 'center',
      fontWeight: '700',
      fontSize: '1.5rem',
      width: '3rem',
      height: '3.5rem',
      minWidth: '3rem',
      minHeight: '3.5rem',
      fontFamily: 'IBM Plex Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      caretColor: '#EA580C',
    },
    otpCodeFieldErrorText: {
      color: '#f87171',
      fontSize: '0.8rem',
      marginTop: '8px',
    },
    verificationLinkStatusText: {
      color: '#a1a1aa',
      fontSize: '0.875rem',
    },
    identityPreview: {
      background: '#27272a',
      border: '1px solid #3f3f46',
      borderRadius: '0.5rem',
      padding: '10px 14px',
    },
    formFieldCheckboxInput: {
      background: '#18181b',
      border: '1px solid #52525b',
      borderRadius: '4px',
    },
    formFieldCheckboxLabel: { color: '#d4d4d8' },
    pageScrollBox: { padding: 0 },
  },
} as const;
