import { ComparisonPage } from './types';

// Rich, competitor-specific comparison data for SEO ranking
const COMPETITOR_DATA: Record<string, Omit<ComparisonPage, 'slug'>> = {
  ticktick: {
    competitor: 'TickTick',
    summary: 'TickTick is a polished task manager with a built-in Pomodoro timer, but it lacks AI goal decomposition, habit coaching, and wellness tracking. Resurgo combines all of this in one app with 4 AI coaches that can actually take action.',
    bestFor: 'People who want more than a task list — AI-powered planning, habit streaks, wellness tracking, and coaching in one unified system.',
    verdict: 'TickTick is excellent for task management and calendar sync. But if you need AI coaching, habit stacking, wellness data, and automated goal decomposition, Resurgo does far more without stitching together multiple apps.',
    categories: [
      { name: 'AI Goal Decomposition', resurgo: 'Automatic milestones + daily tasks from any goal', competitor: 'Manual task entry only' },
      { name: 'Habit Tracking with Streaks', resurgo: 'Built-in with XP, badges, stacking', competitor: 'Basic habits with calendar view' },
      { name: 'AI Coaching Personas', resurgo: '4 action-capable coaches (Nova, Titan, Sage, Phoenix)', competitor: 'No AI coaching' },
      { name: 'Focus Timer Modes', resurgo: 'Pomodoro, Deep Work, Flowtime, custom', competitor: 'Pomodoro only' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, energy, nutrition, steps', competitor: 'Not included' },
      { name: 'Weekly AI Reviews', resurgo: 'Personalized summaries and adjusted focus', competitor: 'Manual review only' },
      { name: 'Gamification (XP/Levels)', resurgo: 'Full XP system + badges + levels', competitor: 'No gamification' },
      { name: 'Free Plan Quality', resurgo: 'Habits, goals, focus, 2 coaches — no expiry', competitor: 'Limited free features' },
      { name: 'Telegram Bot', resurgo: 'Check-in habits from Telegram', competitor: 'Not available' },
    ],
    pricing: { resurgo: 'Free forever + Pro from $4.99/mo or $29.99/yr', competitor: 'Free + Premium $35.99/yr or $5.99/mo' },
    faq: [
      { question: 'Should I switch from TickTick to Resurgo?', answer: 'If you want AI coaching, automatic goal planning, and wellness tracking on top of task management, Resurgo is the upgrade. TickTick is great for tasks — Resurgo handles your whole execution system.' },
      { question: 'Does Resurgo have a Pomodoro timer like TickTick?', answer: 'Yes. Resurgo has Pomodoro (25/5), Deep Work (90-minute blocks), and Flowtime modes — all with distraction logging and ambient sounds.' },
      { question: 'Can I use Resurgo for free like TickTick?', answer: "Yes. Resurgo's free plan includes unlimited habits, goals, all focus timer modes, and 2 AI coaches with no time limit. No credit card required." },
      { question: 'Is Resurgo better than TickTick for habit tracking?', answer: "For habits, Resurgo adds AI suggestions, streak protection (freeze tokens), habit stacking, XP rewards, and coaching — much deeper than TickTick's habit module." },
    ],
  },
  notion: {
    competitor: 'Notion',
    summary: "Notion is a powerful all-in-one workspace for notes and documents, but building a habit and goal system requires significant manual setup. Resurgo is purpose-built for execution with AI automation, no templates needed.",
    bestFor: "People tired of spending hours setting up Notion templates — Resurgo gives you a working AI execution system out of the box in 2 minutes.",
    verdict: "Notion is best for documents, wikis, and flexible databases. Resurgo wins for habit tracking, AI coaching, and automated daily planning. Most users use both — Resurgo for execution, Notion for everything else.",
    categories: [
      { name: 'Setup Time', resurgo: '2 minutes to first goal + habit plan', competitor: 'Hours to build a functional system from scratch' },
      { name: 'AI Goal Breakdown', resurgo: 'Automatic milestones and daily tasks', competitor: 'Manual database entry (Notion AI adds cost)' },
      { name: 'Habit Tracking', resurgo: 'Built-in streaks, XP, stacking, reminders', competitor: 'Requires template + database setup + maintenance' },
      { name: 'AI Coaching', resurgo: '4 dedicated coaches with goal context', competitor: 'Notion AI writes text, no behavioral coaching' },
      { name: 'Focus Timers', resurgo: 'Native Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, steps — all linked', competitor: 'Only if you build a custom database' },
      { name: 'Gamification', resurgo: 'XP, levels, badges for motivation', competitor: 'No gamification' },
      { name: 'Price', resurgo: 'Free forever (full habit + goal features)', competitor: 'Free tier limited; $10-$18/mo for full Notion AI' },
      { name: 'Mobile Experience', resurgo: 'PWA — instant install, works offline', competitor: 'Heavy app, slower mobile experience' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo or Lifetime $49.99', competitor: 'Free tier + Plus $10/mo + AI add-on $10/mo' },
    faq: [
      { question: 'Can Resurgo replace Notion for productivity?', answer: 'For goal tracking, habits, focus, and AI coaching — yes. For note-taking, documentation, and databases — Notion is still great. Many users use Resurgo for daily execution and Notion as a knowledge base.' },
      { question: 'Is Resurgo easier to set up than Notion?', answer: 'Dramatically. Resurgo takes 2 minutes: enter a goal, get an AI plan, start your first habit. Notion requires building or importing a template system that can take hours to maintain.' },
      { question: 'Does Resurgo work for teams like Notion?', answer: 'Currently Resurgo is optimized for individual goal achievement and personal accountability. Notion is better for team wikis and project docs.' },
      { question: 'Does Resurgo have AI like Notion AI?', answer: "Resurgo's AI is focused on behavior and execution — it breaks goals into habits, coaches you on strategy, and adapts your plan based on real progress data. Notion AI is text-focused. Very different use cases." },
    ],
  },
  habitica: {
    competitor: 'Habitica',
    summary: "Habitica gamifies habits with an RPG mechanic, but its retro aesthetic and manual task system can feel dated. Resurgo modernizes gamification with XP, AI coaching, and automated goal planning in a clean terminal UI.",
    bestFor: "People who love gamification but want AI-powered planning rather than manually managing an RPG character alongside their task list.",
    verdict: "Habitica is fun and community-driven. Resurgo takes gamification (XP, levels, badges) and adds AI automation — so you spend less time managing the system and more time executing.",
    categories: [
      { name: 'Gamification Depth', resurgo: 'XP, levels, badges, streak protection', competitor: 'Full RPG — avatar, gear, quests, parties' },
      { name: 'AI Goal Decomposition', resurgo: 'Automatic milestones and daily tasks', competitor: 'Manual task entry only' },
      { name: 'AI Coaching', resurgo: '4 coaches with behavioral strategy', competitor: 'No AI coaching' },
      { name: 'Design & UX', resurgo: 'Modern terminal aesthetic, clean and fast', competitor: 'Retro RPG UI, can feel cluttered' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Weekly Reviews', resurgo: 'AI-generated summaries', competitor: 'Manual only' },
      { name: 'Social / Community', resurgo: 'Individual-focused', competitor: 'Guilds, parties, social quests' },
      { name: 'Mobile PWA', resurgo: 'Install instantly, offline support', competitor: 'Native mobile apps available' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free + Gems/Subscription $4.99/mo' },
    faq: [
      { question: 'Is Resurgo a better alternative to Habitica?', answer: 'If you want AI goal planning and coaching alongside gamification, yes. Habitica excels at social RPG mechanics. Resurgo prioritizes AI-assisted execution with gamification as a motivation layer.' },
      { question: 'Does Resurgo have guilds or social features like Habitica?', answer: "Currently Resurgo focuses on individual performance. Habitica is better if social accountability through parties and guilds is important to you." },
      { question: 'Can I use both Habitica and Resurgo?', answer: "Technically yes, but most users find that Resurgo's gamification combined with AI coaching makes Habitica redundant for their workflow." },
    ],
  },
  todoist: {
    competitor: 'Todoist',
    summary: "Todoist is one of the best pure task managers available. But task management alone doesn't build habits or coach you toward goals. Resurgo layers AI coaching and habit systems on top of structured task planning.",
    bestFor: "People who want a task manager that also builds habits, tracks wellness, and gives AI coaching — not just a checklist.",
    verdict: "Todoist wins for pure task management and cross-platform sync. Resurgo wins for habit formation, AI coaching, goal systems, and wellness. Many power users use Todoist for work tasks and Resurgo for personal goals and habits.",
    categories: [
      { name: 'Task Management Quality', resurgo: 'Full task system with priorities + tags', competitor: 'Industry-leading task management' },
      { name: 'Habit Tracking', resurgo: 'Streaks, stacking, reminders, analytics', competitor: 'No native habit tracking' },
      { name: 'AI Goal Breakdown', resurgo: 'Automatic milestones + daily tasks', competitor: 'AI assistant for writing only' },
      { name: 'AI Coaching', resurgo: '4 coaches with behavioral strategy', competitor: 'No coaching' },
      { name: 'Focus Timer', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Gamification', resurgo: 'XP, levels, streak badges', competitor: 'Karma points (basic)' },
      { name: 'Wellness Integration', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Free Plan', resurgo: 'Full habits + goals + 2 coaches, unlimited', competitor: 'Limited to 5 active projects' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free (limited) + Pro $4/mo + Business $6/mo' },
    faq: [
      { question: 'Is Todoist good for habit tracking?', answer: "Todoist doesn't have a true habit tracking system. Resurgo was built specifically for habits — streaks, scheduling, stacking, and reminders are first-class features, not workarounds." },
      { question: 'Can Resurgo replace Todoist as a task manager?', answer: "Resurgo includes full task management. If you need deep project collaboration, Todoist is more powerful. For personal tasks connected to goals and habits, Resurgo is better." },
      { question: 'Which is cheaper — Todoist or Resurgo?', answer: "Very similar at $4-5/month. Resurgo's free plan is significantly more generous — unlimited habits and goals vs Todoist's 5 project limit." },
    ],
  },
  streaks: {
    competitor: 'Streaks',
    summary: "Streaks is a beautiful iOS-only habit tracker with a strict 12-habit limit. Resurgo is cross-platform, unlimited, adds AI coaching, and doesn't require an Apple device.",
    bestFor: "iOS users who want to move beyond 12 habits and add AI goal planning, coaching, and wellness tracking to their routine.",
    verdict: "Streaks has exceptional Apple Watch integration and minimal iOS UI. Resurgo is better for people who want no habit limit, cross-platform access, AI coaching, and a full goal + wellness system.",
    categories: [
      { name: 'Habit Limit', resurgo: 'Unlimited habits', competitor: 'Max 12 habits' },
      { name: 'Platform Availability', resurgo: 'Any device via PWA (iOS, Android, desktop)', competitor: 'iOS / macOS / watchOS only' },
      { name: 'AI Goal Planning', resurgo: 'Automatic milestones and daily tasks', competitor: 'No goal planning' },
      { name: 'AI Coaching', resurgo: '4 coaches with personalized advice', competitor: 'No coaching' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Android Support', resurgo: 'Full support via PWA', competitor: 'Not available' },
      { name: 'Price', resurgo: 'Free forever tier available', competitor: 'One-time $4.99 (no free tier)' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'One-time $4.99 purchase (iOS only)' },
    faq: [
      { question: 'Is there an alternative to Streaks for Android?', answer: "Resurgo is one of the best Streaks alternatives for Android. It has no habit limit, adds AI coaching and goal planning, and installs as a PWA on any device instantly." },
      { question: 'Why does Streaks limit you to 12 habits?', answer: "Streaks is designed around focusing on fewer, high-impact habits. Resurgo takes a different approach — unlimited habits with AI prioritization to help you focus on what matters most." },
      { question: 'Can Resurgo sync with Apple Watch like Streaks?', answer: "Resurgo uses a PWA approach that works on all platforms via browser. Native Apple Watch integration is on the roadmap. For deep watchOS integration today, Streaks still leads." },
    ],
  },
  habitify: {
    competitor: 'Habitify',
    summary: "Habitify is a clean, data-rich habit tracker with good analytics. But it lacks AI goal planning, coaching, and full wellness integration. Resurgo combines all these into one platform.",
    bestFor: "Habit tracker users who want the analytics depth of Habitify plus AI coaching, goal automation, and a complete wellness system.",
    verdict: "Habitify is great for pure habit analytics. Resurgo adds AI coaching, goal decomposition, wellness tracking, and gamification on top of comparable habit tracking quality.",
    categories: [
      { name: 'Habit Analytics', resurgo: 'Streaks, completion rates, patterns', competitor: 'Advanced charts and trend analysis' },
      { name: 'AI Goal Planning', resurgo: 'Automatic milestones and daily tasks', competitor: 'Not included' },
      { name: 'AI Coaching', resurgo: '6 specialized AI coaches', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, energy, nutrition', competitor: 'Basic mood logging only' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Gamification', resurgo: 'XP, levels, streak badges', competitor: 'Not included' },
      { name: 'Free Plan', resurgo: 'Unlimited habits, goals, 2 coaches', competitor: 'Very limited free tier (3 habits)' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free (3 habits) + Premium $4.99/mo or $39.99/yr' },
    faq: [
      { question: 'How does Resurgo compare to Habitify for data-driven habit tracking?', answer: "Habitify has excellent analytics. Resurgo pairs comparable analytics with AI coaching and goal planning — so you get both the data and the strategy to act on it." },
      { question: 'Does Resurgo have better analytics than Habitify?', answer: "Resurgo provides streak analytics, completion rates, and weekly AI-generated summaries. Habitify shows more granular historical charts. For most users, Resurgo's data + AI insights is more actionable." },
      { question: 'Is Habitify worth it vs Resurgo?', answer: "If pure habit analytics is your only need, Habitify is solid. If you also want goal planning, coaching, focus timers, and wellness tracking, Resurgo delivers more value at the same price point." },
    ],
  },
  reclaim: {
    competitor: 'Reclaim.ai',
    summary: "Reclaim.ai is a smart calendar scheduling tool that automatically finds time for habits and tasks. Resurgo focuses on the behavior layer — building the habits themselves with AI coaching, streaks, and goal decomposition.",
    bestFor: "People who want to build habits via AI coaching and goal systems rather than just schedule blocks in their calendar.",
    verdict: "Reclaim.ai is powerful for calendar automation. Resurgo handles the behavior change itself — building habits that stick, coaching you when you drift, and tracking your wellness alongside goals.",
    categories: [
      { name: 'Calendar Auto-scheduling', resurgo: 'Planned integration', competitor: 'Best-in-class calendar blocking' },
      { name: 'Habit Formation', resurgo: 'Full streaks, stacking, AI coaching', competitor: "Schedules habits, doesn't build them" },
      { name: 'AI Goal Planning', resurgo: 'Decomposes goals into milestones + daily tasks', competitor: 'Time-focused, not goal decomposition' },
      { name: 'AI Coaching', resurgo: '4 behavioral coaches', competitor: 'No coaching' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Gamification', resurgo: 'XP, levels, streak protection', competitor: 'Not included' },
      { name: 'Free Plan', resurgo: 'Generous — habits + goals + coaching', competitor: 'Very limited free tier' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free (very limited) + Starter $8/mo + Business $12/mo' },
    faq: [
      { question: 'Is Resurgo better than Reclaim for habits?', answer: "For building and sustaining habits, absolutely. Reclaim schedules time for habits but doesn't help you build them with coaching, streaks, and behavior analytics." },
      { question: 'Can I use Resurgo alongside Reclaim?', answer: "Yes — they complement each other. Reclaim blocks time for your habits in your calendar; Resurgo helps you actually execute and build those habits through coaching and streaks." },
      { question: 'Why is Reclaim.ai so expensive vs Resurgo?', answer: "Reclaim focuses on calendar intelligence for teams and professionals. Resurgo is priced for individuals focused on personal growth — $4.99/mo vs $8-12/mo for Reclaim's paid tiers." },
    ],
  },
  things3: {
    competitor: 'Things 3',
    summary: "Things 3 is an award-winning task manager exclusive to Apple platforms. Resurgo is cross-platform, adds AI coaching and habit tracking, and doesn't require a $49.99 one-time purchase.",
    bestFor: "Mac/iOS users who want AI habit coaching and goal automation alongside their task management, or anyone on Android/Windows.",
    verdict: "Things 3 is arguably the best pure task manager on Apple. Resurgo is better for habit formation, AI coaching, and cross-platform use — especially if you're not fully in the Apple ecosystem.",
    categories: [
      { name: 'Task Management', resurgo: 'Full task system', competitor: 'Best-in-class Apple task manager' },
      { name: 'Platform Support', resurgo: 'Any device via PWA', competitor: 'iOS / macOS / watchOS only' },
      { name: 'Habit Tracking', resurgo: 'Streaks, stacking, analytics', competitor: 'No habit tracking' },
      { name: 'AI Goal Planning', resurgo: 'Automatic milestones and daily tasks', competitor: 'No AI' },
      { name: 'AI Coaching', resurgo: '4 specialized coaches', competitor: 'No coaching' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, energy, nutrition', competitor: 'Not included' },
      { name: 'Price', resurgo: 'Free tier available, Pro $4.99/mo', competitor: '$49.99 (Mac) + $9.99 (iPhone) + $19.99 (iPad)' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo or Lifetime $49.99', competitor: '$49.99 (Mac) + $9.99 (iPhone) + $19.99 (iPad) — no subscription' },
    faq: [
      { question: 'Is there a Things 3 alternative for Android?', answer: "Resurgo is an excellent Things 3 alternative for Android and cross-platform. It installs instantly as a PWA, includes full task management, and adds AI coaching and habit tracking that Things 3 doesn't have." },
      { question: 'Is Resurgo cheaper than Things 3?', answer: "Resurgo has a full-featured free tier. Things 3 requires purchasing separate apps for each Apple device — potentially $80+ total. Resurgo Pro is $4.99/month or $49.99 lifetime across all platforms." },
      { question: 'Does Resurgo match the quality of Things 3 for task management?', answer: "Things 3 has exceptional depth for Apple ecosystem task management. Resurgo's task system is comprehensive and adds habits, coaching, and goals that Things 3 entirely lacks." },
    ],
  },
  anydo: {
    competitor: 'Any.do',
    summary: "Any.do is a well-designed task manager with a minimal interface and good calendar integration. Resurgo adds AI habit coaching, goal decomposition, and wellness tracking on top of task management.",
    bestFor: "Any.do users looking for a productivity app that also builds habits and provides AI coaching beyond basic task reminders.",
    verdict: "Any.do is a solid task manager with natural language input. Resurgo adds the habit layer, AI coaching, and goal systems that Any.do lacks — making it a more complete productivity platform.",
    categories: [
      { name: 'Task Management', resurgo: 'Full task system', competitor: 'Clean task + calendar integration' },
      { name: 'Habit Tracking', resurgo: 'Streaks, stacking, AI coaching', competitor: 'No habit tracking' },
      { name: 'AI Goal Planning', resurgo: 'Automatic milestones and daily tasks', competitor: 'Basic AI for scheduling only' },
      { name: 'AI Coaching', resurgo: '4 coaches with strategy', competitor: 'No coaching' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Gamification', resurgo: 'XP, levels, streak badges', competitor: 'Not included' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free + Premium $5.99/mo or $2.99/mo annually' },
    faq: [
      { question: 'Can Resurgo replace Any.do?', answer: "For individual productivity including habits and goals, yes. Resurgo includes full task management and adds habit tracking, AI coaching, and wellness monitoring that Any.do doesn't have." },
      { question: 'Is Resurgo free like Any.do?', answer: "Both have free tiers. Resurgo's free tier is more generous — unlimited habits, goals, focus timers, and 2 AI coaches with no time limit." },
      { question: 'Does Resurgo have voice input like Any.do?', answer: "Resurgo focuses on structured goal and habit input. Any.do has a smoother natural language and voice input experience. For voice-first task capture, Any.do is still ahead." },
    ],
  },
  trello: {
    competitor: 'Trello',
    summary: "Trello is a visual kanban board for project management. It's excellent for teams but has no habit tracking, AI coaching, or personal goal systems. Resurgo is purpose-built for personal execution.",
    bestFor: "People using Trello boards to track personal goals who want AI automation, habit streaks, and coaching instead of manual card management.",
    verdict: "Trello and Resurgo serve very different purposes. Trello is a team project management tool; Resurgo is a personal AI execution system. For personal goals and habits, Resurgo is categorically better. For team project boards, Trello still wins.",
    categories: [
      { name: 'Personal Habit Tracking', resurgo: 'Full streak, stacking, analytics', competitor: 'Manual card system only' },
      { name: 'AI Goal Decomposition', resurgo: 'Automatic milestones and daily tasks', competitor: 'Manual board setup' },
      { name: 'AI Coaching', resurgo: '4 behavioral coaches', competitor: 'Not available' },
      { name: 'Team Collaboration', resurgo: 'Individual focused', competitor: 'Best-in-class Kanban boards for teams' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Gamification', resurgo: 'XP, levels, streak badges', competitor: 'Not included' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo', competitor: 'Free + Standard $5/mo + Premium $10/mo' },
    faq: [
      { question: 'Is Trello good for personal habits?', answer: "Not really — Trello requires significant manual setup to track habits and has no streak system, reminders, or AI coaching. Resurgo is purpose-built for personal habits and goals." },
      { question: 'Can I use Resurgo for team goal tracking like Trello?', answer: "Resurgo is optimized for individual performance. For team project boards and collaboration, Trello or Asana is still a better choice. Many users use both — Trello for work projects, Resurgo for personal goals." },
      { question: 'Does Resurgo cost more than Trello?', answer: "Both have solid free tiers. Paid tiers are similar ($4.99-$5/mo). In terms of personal growth features, Resurgo delivers significantly more value." },
    ],
  },
  fabulous: {
    competitor: 'Fabulous',
    summary: "Fabulous is a behavior-change app grounded in behavioral economics research from Duke University. It excels at building morning and evening routines through guided journeys, but lacks AI coaching, goal decomposition, and gamification. Resurgo provides the same science-backed routines plus AI planning and execution tracking.",
    bestFor: "People who love Fabulous's guided routine approach but want AI goal planning, habit stacking, gamification, and wellness data all in one unified system.",
    verdict: "Fabulous is beautifully designed for routine building. Resurgo goes further — adding AI coaching, automatic goal decomposition, XP gamification, and wellness tracking. If you've mastered your morning routine and want to level up your entire life system, Resurgo is the upgrade.",
    categories: [
      { name: 'Morning Routine Builder', resurgo: 'Habit stacking + AI-optimized scheduling', competitor: 'Guided journey-based routine building (Duke research)' },
      { name: 'AI Goal Decomposition', resurgo: 'Automatic milestones and daily tasks from any goal', competitor: 'No goal decomposition' },
      { name: 'AI Coaching Personas', resurgo: '4 action-capable coaches (Nova, Titan, Sage, Phoenix)', competitor: 'No AI coaching' },
      { name: 'Focus Timer Modes', resurgo: 'Pomodoro, Deep Work, Flowtime, custom', competitor: 'Basic focus sessions only' },
      { name: 'Gamification', resurgo: 'Full XP system + badges + levels', competitor: 'Journey-based progress only' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, energy, nutrition, steps', competitor: 'Hydration and basic wellness prompts' },
      { name: 'Customization', resurgo: 'Fully customizable dashboard, widgets, habit stacks', competitor: 'Linear guided journey format' },
      { name: 'Free Plan Quality', resurgo: 'Habits, goals, focus, 2 coaches — no expiry', competitor: 'Very limited free tier, premium required for most features' },
    ],
    pricing: { resurgo: 'Free forever + Pro from $4.99/mo or $29.99/yr', competitor: 'Free (limited) + Premium $12.99/mo or $59.99/yr' },
    faq: [
      { question: 'Is Resurgo better than Fabulous for building habits?', answer: 'Fabulous excels at guided onboarding into routines. Resurgo gives you more freedom — create any habit, stack them, get AI coaching, and track everything with gamification. If you want structure beyond morning routines, Resurgo covers more ground.' },
      { question: 'Does Resurgo have guided journeys like Fabulous?', answer: "Resurgo takes a different approach. Instead of linear journeys, Resurgo's AI coaches create personalized plans based on your specific goals and adapts them as your data changes. It is more flexible but less hand-held than Fabulous's journey system." },
      { question: 'Is Fabulous cheaper than Resurgo?', answer: "Resurgo is significantly cheaper. Resurgo Pro is $4.99/mo vs Fabulous Premium at $12.99/mo. Resurgo also has a more generous free tier and a $49.99 lifetime option that Fabulous doesn't offer." },
      { question: 'Can I switch from Fabulous to Resurgo?', answer: "Yes. If you've built a morning routine with Fabulous and want AI coaching, goal decomposition, and gamification, Resurgo is the natural next step. You can recreate your Fabulous habits in Resurgo in minutes." },
    ],
  },
  finch: {
    competitor: 'Finch',
    summary: "Finch is a self-care app that uses a virtual pet mechanic to encourage emotional wellness habits. It's charming and Gen Z–friendly, but lacks productivity features like AI goal planning, focus timers, and performance tracking. Resurgo bridges the gap between self-care and high-performance execution.",
    bestFor: "Finch users who want to keep the emotional wellness tracking but add serious goal planning, AI coaching, habit analytics, and gamification that drives real results.",
    verdict: "Finch is lovely for emotional check-ins and gentle self-care. Resurgo is for people who want both wellness AND performance — AI-powered goal decomposition, habit streaks with XP, focus timers, and coaching from 4 specialized AI personas. Different ambitions, complementary approaches.",
    categories: [
      { name: 'Emotional Wellness', resurgo: 'Mood, sleep, energy tracking + AI coaching', competitor: 'Virtual pet + gentle prompts + emotional check-ins' },
      { name: 'AI Goal Planning', resurgo: 'Automatic milestones and daily tasks from any goal', competitor: 'No goal decomposition' },
      { name: 'AI Coaching', resurgo: '4 specialized coaches with behavioral strategy', competitor: 'Finch companion provides gentle encouragement' },
      { name: 'Focus Timers', resurgo: 'Pomodoro, Deep Work, Flowtime', competitor: 'Breathing exercises + gentle focus' },
      { name: 'Habit Tracking Depth', resurgo: 'Streaks, stacking, analytics, XP rewards', competitor: 'Basic habit check-offs' },
      { name: 'Gamification', resurgo: 'XP, levels, badges for motivation', competitor: 'Virtual pet growth and customization' },
      { name: 'Nutrition Tracking', resurgo: 'Macro and meal tracking built in', competitor: 'Not included' },
      { name: 'Performance Analytics', resurgo: 'Advanced analytics dashboard with trends', competitor: 'Basic reflections only' },
    ],
    pricing: { resurgo: 'Free forever + Pro from $4.99/mo or $29.99/yr', competitor: 'Free + Finch Plus $4.99/mo or $39.99/yr' },
    faq: [
      { question: 'Is Resurgo a good alternative to Finch?', answer: "If you want emotional wellness features PLUS productivity — goal planning, AI coaching, habit analytics, and focus timers — yes. Resurgo combines self-care with high-performance execution. Finch is better if you only want gentle self-care without productivity pressure." },
      { question: 'Does Resurgo have a virtual pet like Finch?', answer: "Resurgo uses XP, levels, and badges instead of a virtual pet. Both are gamification approaches — Finch uses nurturing (grow your pet), Resurgo uses achievement (level up your life). Different motivational styles for different personalities." },
      { question: 'Can I use both Finch and Resurgo?', answer: "Yes, some users pair Finch for emotional check-ins with Resurgo for goal execution. However, Resurgo's mood and wellness tracking may make Finch redundant for most productivity-minded users." },
    ],
  },
  routinery: {
    competitor: 'Routinery',
    summary: "Routinery is a time-based routine planner that guides you through daily routines step by step with timers. It's excellent for ADHD users and sequential routine followers, but has no AI coaching, goal systems, or analytics. Resurgo adds intelligence to routines with AI planning and behavioral coaching.",
    bestFor: "Routinery users who want to keep structured daily routines but add AI goal decomposition, habit analytics, gamification, and wellness tracking to their system.",
    verdict: "Routinery is best-in-class for step-by-step routine execution with timers. Resurgo is the better choice when you need your routines connected to bigger goals, AI coaching, and a full life management system. Power users often graduate from Routinery to Resurgo when they outgrow pure routine management.",
    categories: [
      { name: 'Routine Timer Guidance', resurgo: 'Focus timers (Pomodoro, Deep Work, Flowtime)', competitor: 'Step-by-step routine timers with visual guidance' },
      { name: 'AI Goal Decomposition', resurgo: 'Automatic milestones and daily tasks from any goal', competitor: 'No goal planning' },
      { name: 'AI Coaching', resurgo: '4 specialized coaches with personalized advice', competitor: 'No AI coaching' },
      { name: 'Habit Analytics', resurgo: 'Streak trends, completion rates, AI insights', competitor: 'Basic completion tracking' },
      { name: 'ADHD Support', resurgo: 'AI-adaptive nudges, micro-task breakdown, streak protection', competitor: 'Step-by-step visual timers (excellent for ADHD)' },
      { name: 'Gamification', resurgo: 'XP, levels, streak badges', competitor: 'Not included' },
      { name: 'Wellness Tracking', resurgo: 'Sleep, mood, nutrition, energy', competitor: 'Not included' },
      { name: 'Free Plan', resurgo: 'Full habits, goals, focus, 2 coaches', competitor: 'Limited to 2 routines on free tier' },
    ],
    pricing: { resurgo: 'Free forever + Pro $4.99/mo or Lifetime $49.99', competitor: 'Free (2 routines) + Premium $7.99/mo or $49.99/yr' },
    faq: [
      { question: 'Is Resurgo better than Routinery for daily routines?', answer: "Routinery is better for pure step-by-step routine execution with visual timers. Resurgo is better when you want your routines connected to goals, AI coaching, and a complete life management system. It depends on whether you need a routine runner or a full execution platform." },
      { question: 'Does Resurgo have step-by-step routine timers like Routinery?', answer: "Resurgo has focus timers (Pomodoro, Deep Work, Flowtime) but not Routinery's specific step-by-step routine guidance. Resurgo's strength is connecting habits to goals with AI coaching rather than micro-managing individual routine steps." },
      { question: 'Is Routinery good for ADHD?', answer: "Routinery is excellent for ADHD due to its visual step-by-step timers. Resurgo approaches ADHD differently — with AI-adaptive nudges, micro-task breakdown, streak protection (freeze tokens), and coaching that responds to your attention patterns. Both are good choices for different ADHD needs." },
      { question: 'Can I switch from Routinery to Resurgo?', answer: "Yes. Recreate your Routinery habits in Resurgo, then benefit from AI goal planning, coaching, analytics, and gamification that Routinery doesn't offer. Many users make this switch when they outgrow pure routine management." },
    ],
  },
};

export const COMPARISON_PAGES: ComparisonPage[] = Object.entries(COMPETITOR_DATA).map(([key, data]) => ({
  slug: `resurgo-vs-${key}`,
  ...data,
}));

export async function getAllComparisons(): Promise<ComparisonPage[]> {
  return COMPARISON_PAGES;
}

export async function getComparisonBySlug(slug: string): Promise<ComparisonPage | null> {
  return COMPARISON_PAGES.find((page) => page.slug === slug) ?? null;
}
