// Stub for convex/_generated/api.
// The real file is auto-generated by `npx convex dev` and is gitignored.
// This file exists only so Jest can resolve the import path.
// Each test that needs specific API references must supply its own
// jest.mock(..., factory) to define the exact shape it requires;
// these empty-object exports are never used directly in tests.
export const api = {} as Record<string, Record<string, unknown>>;
export const internal = {} as Record<string, Record<string, unknown>>;
