"""Build the complete enhanced onboarding page."""
path = r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx"

# Build the complete TSX content
lines = []

# === HEADER ===
lines.append("'use client';")
lines.append("")
lines.append("export const dynamic = 'force-dynamic';")
lines.append("")
lines.append("// ============================================================================")
lines.append("// RESURGO - Premium Onboarding Flow with AI Brain Dump Integration")
lines.append("// 4-step wizard: Welcome -> Brain Dump (+ AI Preview) -> Focus (goal + areas + habits + rhythm) -> Ready")
lines.append("// ============================================================================")
lines.append("")
lines.append("import {useMutation} from 'convex/react';")
lines.append("import {api} from '../../../convex/_generated/api';")
lines.append("import {useRouter} from 'next/navigation';")
lines.append("import {useState, useEffect, useCallback, useRef} from 'react';")
lines.append("import {useStoreUser} from '@/hooks/useStoreUser';")
lines.append("import {useUser} from '@clerk/nextjs';")
lines.append("import {")
lines.append("  ArrowLeft,")
lines.append("  Check,")
lines.append("  Target,")
lines.append("  Dumbbell,")
lines.append("  BookOpen,")
lines.append("  Heart,")
lines.append("  Zap,")
lines.append("  Sparkles,")
lines.append("  Flame,")
lines.append("  Brain,")
lines.append("  Star,")
lines.append("  Moon,")
lines.append("  Eye,")
lines.append("  EyeOff,")
lines.append("  Loader2,")
lines.append("  Lightbulb,")
lines.append("  Send,")
lines.append("  RefreshCw,")
lines.append("  ChevronDown,")
lines.append("  ChevronUp,")
lines.append("  X,")
lines.append("} from 'lucide-react';")
lines.append("")
lines.append("const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;")
lines.append("const hasValidClerkKey =")
lines.append("  !!clerkPublishableKey &&")
lines.append("  clerkPublishableKey.startsWith('pk_') &&")
lines.append("  !/REPLACE_ME|YOUR_PUBLISHABLE_KEY|YOUR_KEY|PLACEHOLDER/i.test(clerkPublishableKey);")
lines.append("")

# === HABIT TEMPLATE DATA ===
lines.append("// Map of habit template IDs to their Convex-compatible data")
lines.append("const HABIT_TEMPLATE_DATA = {")
lines.append("  'morning-routine': {title: 'Morning Routine', description: 'Start your day with intention', category: 'productivity', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 30},")
lines.append("  'exercise-30': {title: 'Exercise 30 min', description: 'Move your body every day', category: 'health', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 30},")
lines.append("  'read-20': {title: 'Read 20 pages', description: 'Build a reading habit', category: 'learning', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 20},")
lines.append("  'meditate': {title: 'Meditate 10 min', description: 'Find your calm center', category: 'wellness', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 10},")
lines.append("  'journal': {title: 'Daily Journal', description: 'Reflect and grow', category: 'wellness', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 15},")
lines.append("  'water-8': {title: 'Drink 8 glasses of water', description: 'Stay hydrated all day', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 1},")
lines.append("  'no-phone-bed': {title: 'No phone in bed', description: 'Better sleep starts here', category: 'wellness', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 1},")
lines.append("  'learn-new': {title: 'Learn something new', description: '15 min of skill building', category: 'learning', frequency: 'daily', timeOfDay: 'afternoon', estimatedMinutes: 15},")
lines.append("  'gratitude': {title: 'Gratitude practice', description: 'Write 3 things grateful for', category: 'wellness', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 5},")
lines.append("  'walk-10k': {title: 'Walk 10,000 steps', description: 'Keep moving through the day', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 60},")
lines.append("  'meal-prep': {title: 'Eat healthy meals', description: 'Nourish your body', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 30},")
lines.append("  'deep-work': {title: 'Deep work session', description: '90 min focused work block', category: 'productivity', frequency: 'weekdays', timeOfDay: 'morning', estimatedMinutes: 90},")
lines.append("};")
lines.append("")

# === TYPES ===
lines.append("// -- Types ---------------------------------------------------------------")
lines.append("")
lines.append("type Step = 'welcome' | 'brain-dump' | 'focus' | 'ready';")
lines.append("const STEPS: Step[] = ['welcome', 'brain-dump', 'focus', 'ready'];")
lines.append("")
lines.append("interface FocusArea {")
lines.append("  id: string;")
lines.append("  label: string;")
lines.append("  description: string;")
lines.append("  icon: React.ReactNode;")
lines.append("  color: string;")
lines.append("}")
lines.append("")
lines.append("interface HabitTemplate {")
lines.append("  id: string;")
lines.append("  name: string;")
lines.append("  icon: React.ReactNode;")
lines.append("  description: string;")
lines.append("  frequency: string;")
lines.append("  focusAreas: string[];")
lines.append("}")
lines.append("")
lines.append("interface AnalysisResult {")
lines.append("  themes: string[];")
lines.append("  goals: string[];")
lines.append("  struggles: string[];")
lines.append("  emotions: string[];")
lines.append("  archetype: string;")
lines.append("  priorityFocus: string[];")
lines.append("  confidence?: number;")
lines.append("  recommendations?: string[];")
lines.append("}")
lines.append("")

# === FOCUS AREAS DATA ===
lines.append("// -- Data --------------------------------------------------------------------")
lines.append("")
lines.append("const FOCUS_AREAS: FocusArea[] = [")
lines.append("  { id: 'habits', label: 'Build Better Habits', description: 'Create routines that stick', icon: <Flame className=\"w-5 h-5\" />, color: 'from-orange-500 to-amber-500' },")
lines.append("  { id: 'goals', label: 'Achieve Big Goals', description: 'Break down & conquer goals', icon: <Target className=\"w-5 h-5\" />, color: 'from-blue-500 to-indigo-500' },")
lines.append("  { id: 'adhd', label: 'Get Organized (ADHD)', description: 'Executive function & focus support', icon: <Brain className=\"w-5 h-5\" />, color: 'from-violet-500 to-purple-500' },")
lines.append("  { id: 'health', label: 'Health & Fitness', description: 'Move more, feel better', icon: <Dumbbell className=\"w-5 h-5\" />, color: 'from-green-500 to-emerald-500' },")
lines.append("  { id: 'productivity', label: 'Boost Productivity', description: 'Get more done, stress less', icon: <Zap className=\"w-5 h-5\" />, color: 'from-yellow-500 to-orange-500' },")
lines.append("  { id: 'learning', label: 'Personal Growth', description: 'Learn & grow every day', icon: <BookOpen className=\"w-5 h-5\" />, color: 'from-purple-500 to-violet-500' },")
lines.append("  { id: 'wellness', label: 'Mental Wellness', description: 'Mindfulness & self-care', icon: <Heart className=\"w-5 h-5\" />, color: 'from-pink-500 to-rose-500' },")
lines.append("];")
lines.append("")

# === HABIT TEMPLATES ===
lines.append("const HABIT_TEMPLATES: HabitTemplate[] = [")
lines.append("  { id: 'morning-routine', name: 'Morning Routine', icon: <Sparkles className=\"w-5 h-5\" />, description: 'Start your day with intention', frequency: 'Daily', focusAreas: ['habits', 'productivity', 'adhd'] },")
lines.append("  { id: 'exercise-30', name: 'Exercise 30 min', icon: <Dumbbell className=\"w-5 h-5\" />, description: 'Move your body every day', frequency: 'Daily', focusAreas: ['health', 'habits'] },")
lines.append("  { id: 'read-20', name: 'Read 20 pages', icon: <BookOpen className=\"w-5 h-5\" />, description: 'Build a reading habit', frequency: 'Daily', focusAreas: ['learning', 'habits'] },")
lines.append("  { id: 'meditate', name: 'Meditate 10 min', icon: <Heart className=\"w-5 h-5\" />, description: 'Find your calm center', frequency: 'Daily', focusAreas: ['wellness', 'habits', 'adhd'] },")
lines.append("  { id: 'journal', name: 'Daily Journal', icon: <Brain className=\"w-5 h-5\" />, description: 'Reflect and grow', frequency: 'Daily', focusAreas: ['wellness', 'learning', 'adhd'] },")
lines.append("  { id: 'water-8', name: 'Drink 8 glasses', icon: <Heart className=\"w-5 h-5\" />, description: 'Stay hydrated all day', frequency: 'Daily', focusAreas: ['health', 'habits', 'adhd'] },")
lines.append("  { id: 'no-phone-bed', name: 'No phone in bed', icon: <Moon className=\"w-5 h-5\" />, description: 'Better sleep starts here', frequency: 'Daily', focusAreas: ['wellness', 'productivity', 'adhd'] },")
lines.append("  { id: 'learn-new', name: 'Learn something new', icon: <Target className=\"w-5 h-5\" />, description: '15 min of skill building', frequency: 'Daily', focusAreas: ['learning', 'goals'] },")
lines.append("  { id: 'gratitude', name: 'Gratitude practice', icon: <Star className=\"w-5 h-5\" />, description: 'Write 3 things grateful for', frequency: 'Daily', focusAreas: ['wellness', 'habits', 'adhd'] },")
lines.append("  { id: 'walk-10k', name: 'Walk 10,000 steps', icon: <Flame className=\"w-5 h-5\" />, description: 'Keep moving through the day', frequency: 'Daily', focusAreas: ['health'] },")
lines.append("  { id: 'meal-prep', name: 'Eat healthy meals', icon: <Heart className=\"w-5 h-5\" />, description: 'Nourish your body', frequency: 'Daily', focusAreas: ['health'] },")
lines.append("  { id: 'deep-work', name: 'Deep work session', icon: <Zap className=\"w-5 h-5\" />, description: '90 min focused work block', frequency: 'Weekdays', focusAreas: ['productivity', 'goals', 'adhd'] },")
lines.append("];")
lines.append("")

# === TIME OPTIONS ===
lines.append("const TIME_OPTIONS = [")
lines.append("  { id: 'early', label: 'Early Bird', description: '5 - 7 AM', icon: <Flame className=\"w-6 h-6\" /> },")
lines.append("  { id: 'morning', label: 'Morning Person', description: '7 - 10 AM', icon: <Sparkles className=\"w-6 h-6\" /> },")
lines.append("  { id: 'afternoon', label: 'Afternoon Riser', description: '12 - 3 PM', icon: <Zap className=\"w-6 h-6\" /> },")
lines.append("  { id: 'evening', label: 'Night Owl', description: '6 - 10 PM', icon: <Moon className=\"w-6 h-6\" /> },")
lines.append("];")
lines.append("")

# === GOAL EXAMPLES ===
lines.append("const GOAL_EXAMPLES = [")
lines.append("  'Get fit and lose weight',")
lines.append("  'Launch my own business',")
lines.append("  'Learn a new language',")
lines.append("  'Read 24 books this year',")
lines.append("  'Build a morning routine',")
lines.append("  'Land my dream job',")
lines.append("  'Save and invest money',")
lines.append("  'Run a half marathon',")
lines.append("];")
lines.append("")

# === DEADLINE OPTIONS ===
lines.append("const DEADLINE_OPTIONS = [")
lines.append("  { id: '1m', label: '1 month', description: 'Quick win' },")
lines.append("  { id: '3m', label: '3 months', description: 'Short sprint' },")
lines.append("  { id: '6m', label: '6 months', description: 'Mid-term push' },")
lines.append("  { id: '1y', label: '1 year', description: 'Long-game' },")
lines.append("  { id: 'ongoing', label: 'Ongoing', description: 'Lifestyle change' },")
lines.append("];")
lines.append("")

# === CN HELPER ===
lines.append("function cn(...classes: (string | boolean | undefined)[]) {")
lines.append("  return classes.filter(Boolean).join(' ');")
lines.append("}")
lines.append("")

content = "\n".join(lines)
print(f"Built {len(content)} chars so far")
with open(r"C:\Users\USER\Documents\GOAKL RTRACKER\scripts\built_part1.txt", 'w', encoding='utf-8') as f:
    f.write(content)
print("Part 1 saved")