#!/usr/bin/env python3
"""Append the component function to the onboarding page."""
import pathlib

PATH = pathlib.Path(r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx")

# Read current content
existing = PATH.read_text(encoding='utf-8')
all_lines = existing.split('\n')

# Find where cn function ends
cn_end = None
for i in range(len(all_lines) - 1, -1, -1):
    if all_lines[i].strip() == '}':
        cn_end = i
        break

print(f"cn function ends at line {cn_end}, total lines: {len(all_lines)}")

# Truncate at cn function end (keep cn function)
all_lines = all_lines[:cn_end + 1]

# Now append the component function
L = all_lines.append

L("")
L("// -- Component ---------------------------------------------------------------")
L("")
L("function OnboardingPageWithAuth() {")
L("  const {user, isLoading} = useStoreUser();")
L("  const {user: clerkUser} = useUser();")
L("  const router = useRouter();")
L("  const completeOnboarding = useMutation(api.users.completeOnboarding);")
L("  const autoGenerateFromOnboarding = useMutation(api.goals.autoGenerateFromOnboarding);")
L("  const createGoal = useMutation(api.goals.create);")
L("  const createHabit = useMutation(api.habits.create);")
L("  const [step, setStep] = useState('welcome');")
L("  const [saving, setSaving] = useState(false);")
L("  const [animating, setAnimating] = useState(false);")
L("  const _goalInputRef = useRef(null);")
L("")
L("  // -- Brain Dump State Variables --")
L("  const [brainDump, setBrainDump] = useState('');")
L("  const [isAnalyzing, setIsAnalyzing] = useState(false);")
L("  const [analysisResult, setAnalysisResult] = useState(null);")
L("  const [showPreview, setShowPreview] = useState(false);")
L("  const [previewFields, setPreviewFields] = useState(null);")
L("")
L("  // Onboarding data")
L("  const [primaryGoal, setPrimaryGoal] = useState('');")
L("  const [primaryGoalReason, setPrimaryGoalReason] = useState('');")
L("  const [primaryGoalDeadline, setPrimaryGoalDeadline] = useState('6m');")
L("  const [lifeVision, setLifeVision] = useState('');")
L("  const [selectedFocus, setSelectedFocus] = useState([]);")
L("  const [selectedHabits, setSelectedHabits] = useState([]);")
L("  const [preferredTime, setPreferredTime] = useState('morning');")
L("")
L("  const [atMaxFocus, setAtMaxFocus] = useState(false);")
L("")
L("  // Brain dump refs")
L("  const brainDumpRef = useRef(null);")
L("  const previewRef = useRef(null);")
L("")
L("  // Redirect if already onboarded")
L("  useEffect(() => {")
L("    if (!isLoading && user?.onboardingComplete) {")
L("      router.replace('/dashboard');")
L("    }")
L("  }, [isLoading, user, router]);")
L("")
L("  // When brain dump analysis arrives, seed preview fields")
L("  useEffect(() => {")
L("    if (analysisResult) {")
L("      setPreviewFields({")
L("        themes: [...analysisResult.themes],")
L("        goals: [...analysisResult.goals],")
L("        struggles: [...analysisResult.struggles],")
L("        emotions: [...analysisResult.emotions],")
L("        archetype: analysisResult.archetype || 'The Explorer',")
L("        focusAreas: [...analysisResult.priorityFocus],")
L("      });")
L("    }")
L("  }, [analysisResult]);")
L("")
L("  const firstName = clerkUser?.firstName || user?.name?.split(' ')[0] || 'there';")
L("")
L("  // Step navigation with animation")
L("  const goToStep = (target) => {")
L("    setAnimating(true);")
L("    setTimeout(() => {")
L("      setStep(target);")
L("      setAnimating(false);")
L("    }, 180);")
L("  };")
L("")
L("  const next = () => {")
L("    const idx = STEPS.indexOf(step);")
L("    if (idx < STEPS.length - 1) goToStep(STEPS[idx + 1]);")
L("  };")
L("")
L("  const back = () => {")
L("    const idx = STEPS.indexOf(step);")
L("    if (idx > 0) goToStep(STEPS[idx - 1]);")
L("  };")
L("")
L("  // Complete onboarding - always redirects, even on failure")
L("  const handleComplete = useCallback(async () => {")
L("    if (saving) return;")
L("    setSaving(true);")
L("    try {")
L("      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;")
L("")
L("      // 1. Save onboarding preferences")
L("      await completeOnboarding({")
L("        primaryGoal: primaryGoal.trim() || undefined,")
L("        primaryGoalReason: primaryGoalReason.trim() || undefined,")
L("        primaryGoalDeadline: primaryGoalDeadline || undefined,")
L("        lifeVision: lifeVision.trim() || undefined,")
L("        focusAreas: selectedFocus.length > 0 ? selectedFocus : undefined,")
L("        selectedHabitTemplates: selectedHabits.length > 0 ? selectedHabits : undefined,")
L("        preferredTime: preferredTime || undefined,")
L("        timezone: tz,")
L("        brainDump: brainDump.trim() || undefined,")
L("        brainDumpAnalysis: analysisResult || undefined,")
L("      });")
L("")
L("      // 2. Auto-generate goal + milestones + starter tasks via AI")
L("      if (primaryGoal.trim()) {")
L("        try {")
L("          await autoGenerateFromOnboarding({")
L("            goalTitle: primaryGoal.trim(),")
L("            goalReason: primaryGoalReason.trim() || undefined,")
L("            goalDeadline: primaryGoalDeadline || undefined,")
L("            focusAreas: selectedFocus.length > 0 ? selectedFocus : undefined,")
L("            preferredTime: preferredTime || undefined,")
L("            brainDumpAnalysis: analysisResult || undefined,")
L("          });")
L("        } catch (err) {")
L("          console.warn('Auto-generate failed, falling back:', err);")
L("          try {")
L("            const deadlineMap = {")
L("              '1m': new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],")
L("              '3m': new Date(Date.now() + 90 * 86400000).toISOString().split('T')[0],")
L("              '6m': new Date(Date.now() + 180 * 86400000).toISOString().split('T')[0],")
L("              '1y': new Date(Date.now() + 365 * 86400000).toISOString().split('T')[0],")
L("            };")
L("            await createGoal({")
L("              title: primaryGoal.trim(),")
L("              description: primaryGoalReason.trim() || undefined,")
L("              category: selectedFocus[0] || 'personal_growth',")
L("              targetDate: deadlineMap[primaryGoalDeadline] || undefined,")
L("              whyImportant: primaryGoalReason.trim() || undefined,")
L("              deadlineType: primaryGoalDeadline === 'ongoing' ? 'ongoing' : 'flexible',")
L("            });")
L("          } catch (fallbackErr) {")
L("            console.warn('Fallback goal creation also failed:', fallbackErr);")
L("          }")
L("        }")
L("      }")
L("")
L("      // 3. Create selected habits in Convex")
L("      for (const habitId of selectedHabits) {")
L("        const template = HABIT_TEMPLATE_DATA[habitId];")
L("        if (!template) continue;")
L("        try {")
L("          await createHabit({")
L("            title: template.title,")
L("            description: template.description,")
L("            category: template.category,")
L("            frequency: template.frequency,")
L("            timeOfDay: template.timeOfDay,")
L("            estimatedMinutes: template.estimatedMinutes,")
L("          });")
L("        } catch (err) {")
L("          console.warn('Habit creation failed for ' + habitId + ':', err);")
L("        }")
L("      }")
L("    } catch (err) {")
L("      console.warn('Onboarding save failed, proceeding anyway:', err);")
L("    }")
L("")
L("    // Track activation metric")
L("    if (typeof window !== 'undefined' && window.gtag) {")
L("      window.gtag('event', 'activation_complete', {")
L("        event_category: 'onboarding',")
L("        primary_focus: selectedFocus[0] || 'none',")
L("        habits_selected: selectedHabits.length,")
L("        has_goal: primaryGoal.trim().length > 0,")
L("        has_brain_dump: (brainDump.trim() || '').length > 0,")
L("        has_ai_analysis: !!analysisResult,")
L("      });")
L("    }")
L("    router.replace('/first-contact');")
L("  }, [saving, completeOnboarding, autoGenerateFromOnboarding, createGoal, createHabit, primaryGoal, primaryGoalReason, primaryGoalDeadline, lifeVision, selectedFocus, selectedHabits, preferredTime, router, brainDump, analysisResult]);")
L("")
L("  // Skip: save whatever we have and go straight to dashboard")
L("  const handleSkip = useCallback(() => {")
L("    handleComplete();")
L("  }, [handleComplete]);")
L("")
L("  // Filter habits based on selected focus areas")
L("  const relevantHabits = selectedFocus.length > 0")
L("    ? HABIT_TEMPLATES.filter(h => h.focusAreas.some(fa => selectedFocus.includes(fa)))")
L("    : HABIT_TEMPLATES;")
L("")
L("  const stepIndex = STEPS.indexOf(step);")
L("  const progress = stepIndex === 0 ? 0 : (stepIndex / (STEPS.length - 1)) * 100;")
L("")
L("  if (isLoading) {")
L("    return (")
L("      <div className=\"flex min-h-screen items-center justify-center bg-black\">")
L("        <p className=\"animate-pulse font-mono text-xs tracking-widest text-orange-600\">Setting up your profile...</p>")
L("      </div>")
L("    );")
L("  }")
L("")
L("  return (")
L("    <div className=\"min-h-screen bg-black text-zinc-100\">")
L("")
L("      {/* PROGRESS BAR (hidden on welcome) */}")
L("      {step !== 'welcome' && (")
L("        <div className=\"fixed left-0 right-0 top-0 z-50 border-b border-zinc-900 bg-black\">")
L("          <div className=\"mx-auto flex max-w-3xl items-center gap-3 px-4 py-3\">")
L("            <button onClick={back} className=\"shrink-0 border border-zinc-800 p-1.5 text-zinc-400 transition hover:border-zinc-700 hover:text-zinc-300\">")
L("              <ArrowLeft className=\"h-4 w-4\" />")
L("            </button>")
L("            <div className=\"flex-1\">")
L("              <div className=\"mb-1 flex justify-between font-mono text-[9px] tracking-widest text-zinc-400\">")
L("                <span>Setup</span>")
L("                <span>Step {stepIndex} of {STEPS.length - 1}</span>")
L("              </div>")
L("              <div className=\"h-px overflow-hidden bg-zinc-900\">")
L("                <div className=\"h-full bg-orange-600 transition-all duration-500 ease-out\" style={{width: `${progress}%`}} />")
L("              </div>")
L("            </div>")
L("            <button onClick={handleSkip} disabled={saving} className=\"shrink-0 font-mono text-[9px] tracking-widest text-zinc-400 transition hover:text-zinc-200 disabled:opacity-40\">")
L("              Skip")
L("            </button>")
L("          </div>")
L("        </div>")
L("      )}")
L("")
L("      {/* CONTENT */}")
L("      <div className={cn(")
L("        'mx-auto max-w-3xl px-5 transition-all duration-200',")
L("        animating ? 'translate-y-3 opacity-0' : 'translate-y-0 opacity-100',")
L("        step !== 'welcome' && 'pt-20'")
L("      )}>")
L("")

PATH.write_text('\n'.join(all_lines), encoding='utf-8')
print(f"Written: {len(all_lines)} lines, {len('\n'.join(all_lines))} chars")