#!/usr/bin/env python3
"""Append Step 3: Focus to the onboarding page."""
import pathlib

PATH = pathlib.Path(r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx")
lines = PATH.read_text(encoding='utf-8').split('\n')
L = lines.append

while lines and lines[-1].strip() == '':
    lines.pop()

L("")
L("        {/* STEP 3: FOCUS */}")
L("        {step === 'focus' && (")
L("          <div className=\"py-10 space-y-10\">")
L("")
L("            {/* AI pre-fill notice */}")
L("            {analysisResult && (")
L("              <div className=\"surface-panel border border-orange-900 bg-orange-950/10 px-4 py-3\">")
L("                <div className=\"flex items-center gap-2 mb-2\">")
L("                  <Brain className=\"h-4 w-4 text-orange-500\" />")
L("                  <span className=\"font-mono text-[9px] tracking-widest text-orange-500\">AI ANALYSIS APPLIED</span>")
L("                </div>")
L("                <p className=\"font-mono text-[10px] text-zinc-400\">")
L("                  Pre-populated from your brain dump. Edit anything that doesn&apos;t look right.")
L("                </p>")
L("                <button")
L("                  onClick={() => { setAnalysisResult(null); setPreviewFields(null); }}")
L("                  className=\"mt-2 font-mono text-[9px] tracking-widest text-orange-600 underline underline-offset-2 hover:text-orange-400\"")
L("                >")
L("                  Clear AI suggestions")
L("                </button>")
L("              </div>")
L("            )}")
L("")
# Section A: Your Goal
L("            <section>")
L("              <div className=\"surface-panel mb-4\">")
L("                <div className=\"flex items-center gap-2 border-b border-zinc-900 px-4 py-2\">")
L("                  <span className=\"h-1.5 w-1.5 rounded-full bg-orange-600\" />")
L("                  <span className=\"font-mono text-[9px] tracking-widest text-orange-600\">B &middot; YOUR GOAL</span>")
L("                </div>")
L("                <div className=\"px-4 py-3\">")
L("                  <h2 className=\"font-mono text-lg font-bold tracking-tight text-zinc-100\">What&apos;s your #1 goal?</h2>")
L("                  <p className=\"mt-0.5 font-mono text-[10px] text-zinc-400\">You can always add more later.</p>")
L("                </div>")
L("              </div>")
L("")
L("              <div className=\"mb-3 flex flex-wrap gap-2\">")
L("                {GOAL_EXAMPLES.map((ex) => (")
L("                  <button")
L("                    key={ex}")
L("                    onClick={() => setPrimaryGoal(ex)}")
L("                    className={cn(")
L("                      'border px-2.5 py-1 font-mono text-[9px] tracking-widest transition',")
L("                      primaryGoal === ex")
L("                        ? 'border-orange-800 bg-orange-950/30 text-orange-500'")
L("                        : 'border-zinc-800 text-zinc-400 hover:border-zinc-700 hover:text-zinc-400'")
L("                    )}")
L("                  >")
L("                    {ex}")
L("                  </button>")
L("                ))}")
L("              </div>")
L("")
L("              <textarea")
L("                value={primaryGoal}")
L("                onChange={(e) => setPrimaryGoal(e.target.value)}")
L("                placeholder=\"e.g. Get fit and feel more energetic every day...\"")
L("                rows={2}")
L("                className=\"mb-3 w-full resize-none border border-zinc-800 bg-black px-4 py-3 font-mono text-xs text-zinc-300 placeholder-zinc-700 outline-none transition focus:border-orange-800\"")
L("              />")
L("")
L("              <textarea")
L("                value={primaryGoalReason}")
L("                onChange={(e) => setPrimaryGoalReason(e.target.value)}")
L("                placeholder=\"Why this matters to you (optional)...\"")
L("                rows={1}")
L("                className=\"mb-3 w-full resize-none border border-zinc-800 bg-black px-4 py-2 font-mono text-[10px] text-zinc-300 placeholder-zinc-700 outline-none transition focus:border-orange-800\"")
L("              />")
L("")
L("              <div className=\"grid grid-cols-3 gap-2 sm:grid-cols-5\">")
L("                {DEADLINE_OPTIONS.map((d) => (")
L("                  <button")
L("                    key={d.id}")
L("                    onClick={() => setPrimaryGoalDeadline(d.id)}")
L("                    className={cn(")
L("                      'flex flex-col items-center gap-0.5 border py-2 font-mono text-center transition',")
L("                      primaryGoalDeadline === d.id")
L("                        ? 'border-orange-800 bg-orange-950/30 text-orange-500'")
L("                        : 'border-zinc-800 bg-zinc-950 text-zinc-400 hover:border-zinc-700'")
L("                    )}")
L("                  >")
L("                    <span className=\"text-[10px] font-bold\">{d.label}</span>")
L("                    <span className=\"text-[8px] text-zinc-400\">{d.description}</span>")
L("                  </button>")
L("                ))}")
L("              </div>")
L("            </section>")
L("")
# Section B: Focus Areas
L("            <section>")
L("              <div className=\"surface-panel mb-4\">")
L("                <div className=\"flex items-center gap-2 border-b border-zinc-900 px-4 py-2\">")
L("                  <span className=\"h-1.5 w-1.5 rounded-full bg-orange-600\" />")
L("                  <span className=\"font-mono text-[9px] tracking-widest text-orange-600\">C &middot; FOCUS AREAS</span>")
L("                </div>")
L("                <div className=\"flex items-center justify-between px-4 py-3\">")
L("                  <div>")
L("                    <h2 className=\"font-mono text-lg font-bold tracking-tight text-zinc-100\">Pick your focus areas</h2>")
L("                    <p className=\"mt-0.5 font-mono text-[10px] text-zinc-400\">Pick up to 3 &middot; personalises your AI coaching</p>")
L("                  </div>")
L("                  <span className={cn('font-mono text-[10px] tracking-widest border px-2 py-0.5', selectedFocus.length >= 3 ? 'border-orange-800 text-orange-500 bg-orange-950/30' : 'border-zinc-800 text-zinc-400')}>{selectedFocus.length}/3</span>")
L("                </div>")
L("              </div>")
L("")
L("              <div className=\"mb-3 grid grid-cols-1 gap-1 sm:grid-cols-2\">")
L("                {FOCUS_AREAS.map((area) => {")
L("                  const isSelected = selectedFocus.includes(area.id);")
L("                  return (")
L('                    <button')
L("                      key={area.id}")
L("                      onClick={() => {")
L("                        setSelectedFocus(prev => {")
L("                          if (isSelected) return prev.filter(id => id !== area.id);")
L("                          if (prev.length >= 3) {")
L("                            setAtMaxFocus(true);")
L("                            setTimeout(() => setAtMaxFocus(false), 2500);")
L("                            return prev;")
L("                          }")
L("                          return [...prev, area.id];")
L("                        });")
L("                      }}")
L('                      className={cn("flex items-center gap-3 border px-4 py-3 text-left transition", isSelected ? "border-orange-800 bg-orange-950/20 text-orange-500" : "border-zinc-800 bg-zinc-950 text-zinc-500 hover:border-zinc-700 hover:text-zinc-300")}')
L("                    >")
L("                      <div className=\"flex-1\">")
L("                        <div className=\"font-mono text-xs font-semibold tracking-wider\">{area.label}</div>")
L("                        <div className=\"font-mono text-[9px] text-zinc-400\">{area.description}</div>")
L("                      </div>")
L("                      {isSelected && <Check className=\"h-3 w-3 shrink-0 text-orange-500\" />}")
L("                    </button>")
L("                  )}")
L("                })}")
L("              </div>")
L("")
L("              {atMaxFocus && (")
L("                <p className=\"mb-2 font-mono text-[9px] tracking-wider text-amber-500 text-center\">Max 3 areas selected &mdash; deselect one to choose another.</p>")
L("              )}")
L("")
L("              {analysisResult && previewFields?.focusAreas?.length > 0 && selectedFocus.length === 0 && (")
L("                <p className=\"mb-2 font-mono text-[9px] text-cyan-500 text-center\">AI suggested focus areas &mdash; click Apply in Brain Dump step or select manually</p>")
L("              )}")
L("")
L('              <textarea')
L('                value={lifeVision}')
L('                onChange={(e) => setLifeVision(e.target.value)}')
L('                placeholder="1-year vision &mdash; where will you be? (optional)"')
L('                rows={2}')
L('                className="mt-3 w-full border border-zinc-800 bg-black px-3 py-2 font-mono text-[10px] text-zinc-300 placeholder-zinc-700 outline-none transition focus:border-orange-800 resize-none"')
L("              />")
L("            </section>")
L("")

PATH.write_text('\n'.join(lines), encoding='utf-8')
print(f"Step 3 part 1 appended: {len(lines)} lines")