#!/usr/bin/env python3
"""Append Step 1: Welcome to the onboarding page."""
import pathlib

PATH = pathlib.Path(r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx")
lines = PATH.read_text(encoding='utf-8').split('\n')
L = lines.append

# Remove the trailing empty line from previous content if it exists
while lines and lines[-1].strip() == '':
    lines.pop()

L("")
L("        {/* STEP 1: WELCOME */}")
L("        {step === 'welcome' && (")
L("          <div className=\"flex min-h-screen flex-col items-center justify-center py-16 text-center\">")
L("            <div className=\"surface-panel mb-8 w-full max-w-md p-6\">")
L("              <div className=\"mb-4 flex items-center gap-2\">")
L("                <span className=\"h-1.5 w-1.5 animate-pulse rounded-full bg-orange-600\" />")
L("                <span className=\"font-mono text-[9px] tracking-widest text-orange-600\">RESURGO · GETTING STARTED</span>")
L("              </div>")
L("              <div className=\"space-y-1 text-left\">")
L("                {['Loading modules...', 'Initialising habit engine...', 'Calibrating AI coach...', 'Profile ready'].map((msg, i) => (")
L("                  <div key={msg} className={`font-mono text-[10px] tracking-wider ${i === 3 ? 'text-green-500' : 'text-zinc-400'}`}>")
L("                    {i < 3 ? <span className=\"mr-2 text-green-700\">[OK]</span> : <span className=\"mr-2 animate-pulse text-green-500\">[OK]</span>}")
L("                    {msg}")
L("                  </div>")
L("                ))}")
L("              </div>")
L("            </div>")
L("")
L("            <h1 className=\"mb-2 font-mono text-4xl font-black tracking-tight text-zinc-100 sm:text-5xl\">")
L("              WELCOME, <span className=\"text-orange-500\">{firstName.toUpperCase()}</span>")
L("            </h1>")
L("            <p className=\"mb-3 max-w-lg font-mono text-xs tracking-widest text-zinc-400\">")
L("              Your personal life OS quick setup, calmer dashboard, better defaults.")
L("            </p>")
L("            <p className=\"mb-8 max-w-xl font-terminal text-sm leading-relaxed text-zinc-400\">")
L("              We&apos;ll set one meaningful goal, pick a few focus areas, and give your workspace enough structure to feel useful from day one.")
L("            </p>")
L("")
L("            <div className=\"mb-10 flex flex-wrap justify-center gap-2\">")
L("              {[")
L("                { text: 'AI Goal Breakdown' },")
L("                { text: 'Habit Streaks' },")
L("                { text: 'Smart Analytics' },")
L("                { text: 'AI Coaching' },")
L("              ].map((f) => (")
L("                <div key={f.text} className=\"border border-zinc-800 bg-zinc-950 px-3 py-1.5 font-mono text-[9px] tracking-widest text-zinc-400\">")
L("                  {f.text}")
L("                </div>")
L("              ))}")
L("            </div>")
L("")
L("            <button")
L("              onClick={next}")
L("              className=\"mb-3 border border-orange-800 bg-orange-950/30 px-8 py-3 font-mono text-xs tracking-widest text-orange-500 transition hover:bg-orange-950/50\"")
L("            >")
L("              [Get Started]")
L("            </button>")
L("            <button onClick={handleSkip} className=\"font-mono text-[9px] tracking-widest text-zinc-600 hover:text-zinc-400 mt-2 transition\">")
L("              I&apos;ll set this later &rarr;")
L("            </button>")
L("          </div>")
L("        )}")
L("")

PATH.write_text('\n'.join(lines), encoding='utf-8')
print(f"Step 1 appended: {len(lines)} lines, {len('\\n'.join(lines))} chars")