#!/usr/bin/env python3
"""Append Step 3 continued and Step 4: Ready to the onboarding page."""
import pathlib

PATH = pathlib.Path(r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx")
lines = PATH.read_text(encoding='utf-8').split('\n')
L = lines.append

while lines and lines[-1].strip() == '':
    lines.pop()

# Section C: Starter Habits
L("")
L("            <section>")
L("              <div className=\"surface-panel mb-4\">")
L("                <div className=\"flex items-center gap-2 border-b border-zinc-900 px-4 py-2\">")
L("                  <span className=\"h-1.5 w-1.5 rounded-full bg-orange-600\" />")
L("                  <span className=\"font-mono text-[9px] tracking-widest text-orange-600\">D &middot; STARTER HABITS</span>")
L("                </div>")
L("                <div className=\"px-4 py-3\">")
L("                  <h2 className=\"font-mono text-lg font-bold tracking-tight text-zinc-100\">Pick your starter habits</h2>")
L("                  <p className=\"mt-0.5 font-mono text-[10px] text-zinc-400\">")
L("                    {selectedFocus.length > 0 ? 'Curated for your focus areas &middot; start small' : 'Choose habits to begin today'}")
L("                  </p>")
L("                </div>")
L("              </div>")
L("")
L("              <div className=\"mb-3 divide-y divide-zinc-900 border border-zinc-900\">")
L("                {relevantHabits.map((habit) => {")
L("                  const isSelected = selectedHabits.includes(habit.id);")
L("                  return (")
L('                    <button')
L("                      key={habit.id}")
L("                      onClick={() => {")
L("                        setSelectedHabits(prev =>")
L("                          isSelected ? prev.filter(id => id !== habit.id) : [...prev, habit.id]")
L("                        );")
L("                      }}")
L('                      className={cn("flex w-full items-center gap-3 px-4 py-3 text-left transition", isSelected ? "bg-orange-950/20" : "bg-zinc-950 hover:bg-zinc-900")}')
L("                    >")
L('                      <div className={cn("h-3 w-3 shrink-0 border", isSelected ? "border-orange-600 bg-orange-950/60" : "border-zinc-700")} />')
L("                      <div className=\"flex-1\">")
L('                        <p className={cn("font-mono text-xs", isSelected ? "text-orange-400" : "text-zinc-400")}>{habit.name}</p>')
L('                        <p className="font-mono text-[9px] text-zinc-400">{habit.description}</p>')
L("                      </div>")
L('                      <span className="shrink-0 border border-zinc-800 px-1.5 py-0.5 font-mono text-[8px] text-zinc-400">{habit.frequency.toUpperCase()}</span>')
L("                    </button>")
L("                  )}")
L("                })}")
L("              </div>")
L("")
L("              {selectedHabits.length > 0 && (")
L('                <div className="border border-orange-900 bg-orange-950/10 px-4 py-2">')
L('                  <p className="font-mono text-[10px] tracking-widest text-orange-600">')
L("                    {selectedHabits.length}_HABIT{selectedHabits.length !== 1 ? 'S' : ''}_SELECTED :: START_SMALL_FOR_BEST_RESULTS")
L("                  </p>")
L("                </div>")
L("              )}")
L("            </section>")
L("")

# Section D: Daily Rhythm
L("            <section>")
L("              <div className=\"surface-panel mb-4\">")
L("                <div className=\"flex items-center gap-2 border-b border-zinc-900 px-4 py-2\">")
L("                  <span className=\"h-1.5 w-1.5 rounded-full bg-orange-600\" />")
L("                  <span className=\"font-mono text-[9px] tracking-widest text-orange-600\">E &middot; DAILY RHYTHM</span>")
L("                </div>")
L("                <div className=\"px-4 py-3\">")
L("                  <h2 className=\"font-mono text-lg font-bold tracking-tight text-zinc-100\">When are you most productive?</h2>")
L("                  <p className=\"mt-0.5 font-mono text-[10px] text-zinc-400\">We&apos;ll schedule check-ins around your peak energy</p>")
L("                </div>")
L("              </div>")
L("")
L("              <div className=\"grid grid-cols-2 gap-2 sm:grid-cols-4\">")
L("                {TIME_OPTIONS.map((time) => {")
L("                  const isSelected = preferredTime === time.id;")
L("                  return (")
L('                    <button')
L("                      key={time.id}")
L("                      onClick={() => setPreferredTime(time.id)}")
L('                      className={cn("flex flex-col items-center gap-1 border py-4 transition", isSelected ? "border-orange-800 bg-orange-950/20 text-orange-500" : "border-zinc-800 bg-zinc-950 text-zinc-500 hover:border-zinc-700")}')
L("                    >")
L("                      <div className=\"font-mono text-xs font-bold tracking-widest\">{time.label}</div>")
L("                      <div className=\"font-mono text-[9px] text-zinc-400\">{time.description}</div>")
L("                    </button>")
L("                  )}")
L("                })}")
L("              </div>")
L("            </section>")
L("")

# Continue button
L("            <div className=\"flex flex-col items-center gap-3 pt-2\">")
L("              <button onClick={next} className=\"border border-orange-800 bg-orange-950/30 px-10 py-3 font-mono text-xs tracking-widest text-orange-500 transition hover:bg-orange-950/50\">")
L("                [Continue]")
L("              </button>")
L('              <button onClick={next} className="font-mono text-[9px] tracking-widest text-zinc-500 transition hover:text-zinc-300 underline-offset-2 hover:underline">')
L("                I&apos;ll configure later &rarr;")
L("              </button>")
L("            </div>")
L("          </div>")
L("        )}")
L("")

# STEP 4: READY
L("        {/* STEP 4: READY */}")
L("        {step === 'ready' && (")
L('          <div className="flex min-h-[80vh] flex-col justify-center py-10 relative overflow-hidden">')
L("")
L("            {/* Confetti particles */}")
L('            <div className="pointer-events-none absolute inset-0" aria-hidden="true">')
L("              {Array.from({ length: 24 }).map((_, i) => (")
L("                <div")
L("                  key={i}")
L('                  className="absolute h-1.5 w-1.5 rounded-full animate-bounce"')
L("                  style={{")
L("                    left: `${8 + (i * 37) % 84}%`,")
L("                    top: `${5 + (i * 23) % 70}%`,")
L("                    backgroundColor: ['#f97316', '#eab308', '#22c55e', '#3b82f6', '#a855f7', '#ec4899'][i % 6],")
L("                    animationDelay: `${i * 0.15}s`,")
L("                    animationDuration: `${1.5 + (i % 3) * 0.5}s`,")
L("                    opacity: 0.6,")
L("                  }}")
L("                />")
L("              ))}")
L("            </div>")
L("")
L('            <div className="mb-8 text-center relative z-10">')
L('              <div className="mb-4 flex items-center justify-center gap-2">')
L('                <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-green-500" />')
L('                <span className="font-mono text-[9px] tracking-widest text-green-600">SYSTEM READY</span>')
L("              </div>")
L("")
L("              {/* XP Badge */}")
L('              <div className="mx-auto mb-5 inline-flex items-center gap-2 border border-orange-800 bg-orange-950/30 px-5 py-2">')
L('                <span className="text-lg">&#x1F3C6;</span>')
L('                <span className="font-mono text-sm font-bold tracking-widest text-orange-500">+50 XP</span>')
L('                <span className="font-mono text-[9px] text-zinc-400">ONBOARDING COMPLETE</span>')
L("              </div>")
L("")
L('              <h2 className="font-mono text-3xl font-black tracking-tight text-zinc-100">')
L("                You&apos;re ready, <span className=\"text-orange-500\">{firstName}</span>")
L("              </h2>")
L('              <p className="mt-2 font-mono text-xs text-zinc-400">Your AI coach is standing by &middot; let&apos;s make today count</p>')
L("            </div>")
L("")
L("            {/* Summary */}")
L('            <div className="mx-auto mb-8 w-full max-w-md space-y-px">')
L("              {primaryGoal && (")
L('                <div className="surface-panel p-4">')
L('                  <p className="mb-1.5 font-mono text-[9px] tracking-widest text-zinc-400">YOUR GOAL</p>')
L('                  <p className="font-mono text-xs text-zinc-300">{primaryGoal}</p>')
L("                  {primaryGoalReason && <p className=\"mt-1 font-mono text-[9px] text-zinc-400\">Why: {primaryGoalReason}</p>}")
L("                  {primaryGoalDeadline && (")
L('                    <span className="mt-1.5 inline-block border border-orange-900 bg-orange-950/20 px-2 py-0.5 font-mono text-[9px] text-orange-600">')
L("                      {DEADLINE_OPTIONS.find(d => d.id === primaryGoalDeadline)?.label.toUpperCase()}")
L("                    </span>")
L("                  )}")
L("                </div>")
L("              )}")
L("")
L("              {selectedFocus.length > 0 && (")
L('                <div className="surface-panel p-4">')
L('                  <p className="mb-1.5 font-mono text-[9px] tracking-widest text-zinc-400">FOCUS AREAS</p>')
L('                  <div className="flex flex-wrap gap-1.5">')
L("                    {selectedFocus.map(id => {")
L("                      const area = FOCUS_AREAS.find(a => a.id === id);")
L("                      return area ? (")
L('                        <span key={id} className="border border-zinc-800 px-2 py-0.5 font-mono text-[9px] text-zinc-500">{area.label}</span>')
L("                      ) : null;")
L("                    })}")
L("                  </div>")
L("                </div>")
L("              )}")
L("")
L("              {selectedHabits.length > 0 && (")
L('                <div className="surface-panel p-4">')
L('                  <p className="mb-1.5 font-mono text-[9px] tracking-widest text-zinc-400">HABITS ({selectedHabits.length})</p>')
L('                  <div className="flex flex-wrap gap-x-4 gap-y-0.5">')
L("                    {selectedHabits.slice(0, 5).map(id => {")
L("                      const h = HABIT_TEMPLATES.find(t => t.id === id);")
L("                      return h ? <span key={id} className=\"font-mono text-[10px] text-zinc-400\">{h.name}</span> : null;")
L("                    })}")
L("                    {selectedHabits.length > 5 && <span className=\"font-mono text-[10px] text-zinc-400\">+{selectedHabits.length - 5} more</span>}")
L("                  </div>")
L("                </div>")
L("              )}")
L("")
L("              {brainDump.trim().length > 0 && (")
L('                <div className="surface-panel p-4">')
L('                  <p className="mb-1.5 font-mono text-[9px] tracking-widest text-zinc-400">BRAIN DUMP SUMMARY</p>')
L('                  <p className="font-mono text-xs text-zinc-400 whitespace-pre-wrap">{brainDump}</p>')
L("                  {analysisResult && (")
L('                    <div className="mt-2 flex flex-wrap gap-1">')
L("                      <span className=\"font-mono text-[8px] border border-cyan-800 bg-cyan-950/20 px-1.5 py-0.5 text-cyan-500\">{analysisResult.archetype}</span>")
L("                      <span className=\"font-mono text-[8px] border border-zinc-800 bg-zinc-950 px-1.5 py-0.5 text-zinc-500\">{analysisResult.themes?.length || 0} themes</span>")
L("                      <span className=\"font-mono text-[8px] border border-zinc-800 bg-zinc-950 px-1.5 py-0.5 text-zinc-500\">{analysisResult.goals?.length || 0} goals</span>")
L("                    </div>")
L("                  )}")
L("                </div>")
L("              )}")
L("")
L('              <div className="surface-panel p-4">')
L('                <p className="mb-1 font-mono text-[9px] tracking-widest text-zinc-400">DAILY RHYTHM</p>')
L('                <p className="font-mono text-xs text-zinc-400">')
L("                  {TIME_OPTIONS.find(t => t.id === preferredTime)?.label} &middot; {TIME_OPTIONS.find(t => t.id === preferredTime)?.description}")
L("                </p>")
L("              </div>")
L("")
L("              {!primaryGoal && selectedFocus.length === 0 && selectedHabits.length === 0 && (")
L('                <div className="surface-panel p-4 text-center">')
L("                  <p className=\"font-mono text-xs text-zinc-400\">You can configure goals and habits from your dashboard at any time</p>")
L("                </div>")
L("              )}")
L("            </div>")
L("")
L('            <div className="flex flex-col items-center gap-3">')
L("              <button")
L("                onClick={handleComplete}")
L("                disabled={saving}")
L('                className="border border-orange-800 bg-orange-950/30 px-10 py-3 font-mono text-xs tracking-widest text-orange-500 transition hover:bg-orange-950/50 disabled:cursor-not-allowed disabled:opacity-60"')
L("              >")
L("                {saving ? '[Launching...]' : '[Start My Journey]'}")
L("              </button>")
L('              <p className="font-mono text-[9px] text-zinc-400">You can update your preferences any time in Settings</p>')
L("            </div>")
L("          </div>")
L("        )}")
L("")
L("}")  # Close OnboardingPageWithAuth
L("")

# Export default function
L("export default function OnboardingPage() {")
L("  if (!hasValidClerkKey) {")
L("    return (")
L('      <div className="flex min-h-screen items-center justify-center bg-black px-4">')
L('        <div className="w-full max-w-lg rounded-xl border border-red-900/50 bg-red-950/20 p-5">')
L('          <p className="font-mono text-[10px] tracking-widest text-red-400">AUTH_CONFIG_ERROR</p>')
L('          <h1 className="mt-2 font-mono text-lg text-zinc-100">Onboarding is unavailable</h1>')
L('          <p className="mt-2 font-mono text-xs leading-relaxed text-zinc-300">')
L("            Clerk is not configured correctly in this environment. Set a valid")
L('            <span className="mx-1 rounded bg-black/40 px-1.5 py-0.5 text-zinc-100">NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY</span>')
L("            and")
L('            <span className="mx-1 rounded bg-black/40 px-1.5 py-0.5 text-zinc-100">CLERK_JWT_ISSUER_DOMAIN</span>')
L("            then redeploy.")
L("          </p>")
L("        </div>")
L("      </div>")
L("    )")
L("  }")
L("")
L("  return <OnboardingPageWithAuth />;")
L("}")

PATH.write_text('\n'.join(lines), encoding='utf-8')
content = '\n'.join(lines)
print(f"Complete! {len(lines)} lines, {len(content)} chars")
print(f"export default count: {content.count('export default function')}")
print(f"function OnboardingPageWithAuth count: {content.count('function OnboardingPageWithAuth')}")