#!/usr/bin/env python3
"""Write the complete enhanced onboarding page."""
import pathlib

path = pathlib.Path(r"C:\Users\USER\Documents\GOAKL RTRACKER\src\app\onboarding\page.tsx")

# Read existing to get current state
current = path.read_text(encoding='utf-8')
print(f"Current file: {len(current)} chars, first 50: {current[:50]!r}")
print("About to write complete file...")

# We will write the complete file content here
# Using a function to build it properly
def build_file():
    INDENT = "  "  # 2 spaces for inside component

    lines = []
    L = lines.append

    # == HEADER ==
    L("'use client';")
    L("")
    L("export const dynamic = 'force-dynamic';")
    L("")
    L("// ============================================================================")
    L("// RESURGO - Premium Onboarding Flow with AI Brain Dump Integration")
    L("// 4-step wizard: Welcome -> Brain Dump (+ AI Preview) -> Focus -> Ready")
    L("// ============================================================================")
    L("")
    L("import {useMutation} from 'convex/react';")
    L("import {api} from '../../../convex/_generated/api';")
    L("import {useRouter} from 'next/navigation';")
    L("import {useState, useEffect, useCallback, useRef} from 'react';")
    L("import {useStoreUser} from '@/hooks/useStoreUser';")
    L("import {useUser} from '@clerk/nextjs';")
    L("import {")
    L("  ArrowLeft,")
    L("  Check,")
    L("  Target,")
    L("  Dumbbell,")
    L("  BookOpen,")
    L("  Heart,")
    L("  Zap,")
    L("  Sparkles,")
    L("  Flame,")
    L("  Brain,")
    L("  Star,")
    L("  Moon,")
    L("  Eye,")
    L("  EyeOff,")
    L("  Loader2,")
    L("  Lightbulb,")
    L("  Send,")
    L("  RefreshCw,")
    L("  ChevronDown,")
    L("  ChevronUp,")
    L("  ChevronRight,")
    L("  X,")
    L("} from 'lucide-react';")
    L("")
    L("const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;")
    L("const hasValidClerkKey =")
    L("  !!clerkPublishableKey &&")
    L("  clerkPublishableKey.startsWith('pk_') &&")
    L("  !/REPLACE_ME|YOUR_PUBLISHABLE_KEY|YOUR_KEY|PLACEHOLDER/i.test(clerkPublishableKey);")
    L("")

    # HABIT TEMPLATE DATA
    L("const HABIT_TEMPLATE_DATA = {")
    L("  'morning-routine': {title: 'Morning Routine', description: 'Start your day with intention', category: 'productivity', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 30},")
    L("  'exercise-30': {title: 'Exercise 30 min', description: 'Move your body every day', category: 'health', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 30},")
    L("  'read-20': {title: 'Read 20 pages', description: 'Build a reading habit', category: 'learning', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 20},")
    L("  'meditate': {title: 'Meditate 10 min', description: 'Find your calm center', category: 'wellness', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 10},")
    L("  'journal': {title: 'Daily Journal', description: 'Reflect and grow', category: 'wellness', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 15},")
    L("  'water-8': {title: 'Drink 8 glasses of water', description: 'Stay hydrated all day', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 1},")
    L("  'no-phone-bed': {title: 'No phone in bed', description: 'Better sleep starts here', category: 'wellness', frequency: 'daily', timeOfDay: 'evening', estimatedMinutes: 1},")
    L("  'learn-new': {title: 'Learn something new', description: '15 min of skill building', category: 'learning', frequency: 'daily', timeOfDay: 'afternoon', estimatedMinutes: 15},")
    L("  'gratitude': {title: 'Gratitude practice', description: 'Write 3 things grateful for', category: 'wellness', frequency: 'daily', timeOfDay: 'morning', estimatedMinutes: 5},")
    L("  'walk-10k': {title: 'Walk 10,000 steps', description: 'Keep moving through the day', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 60},")
    L("  'meal-prep': {title: 'Eat healthy meals', description: 'Nourish your body', category: 'health', frequency: 'daily', timeOfDay: 'anytime', estimatedMinutes: 30},")
    L("  'deep-work': {title: 'Deep work session', description: '90 min focused work block', category: 'productivity', frequency: 'weekdays', timeOfDay: 'morning', estimatedMinutes: 90},")
    L("};")
    L("")

    # TYPES
    L("// -- Types -------------------------------------------------------------------")
    L("")
    L("type Step = 'welcome' | 'brain-dump' | 'focus' | 'ready';")
    L("const STEPS: Step[] = ['welcome', 'brain-dump', 'focus', 'ready'];")
    L("")
    L("interface FocusArea {")
    L("  id: string;")
    L("  label: string;")
    L("  description: string;")
    L("  icon: React.ReactNode;")
    L("  color: string;")
    L("}")
    L("")
    L("interface HabitTemplate {")
    L("  id: string;")
    L("  name: string;")
    L("  icon: React.ReactNode;")
    L("  description: string;")
    L("  frequency: string;")
    L("  focusAreas: string[];")
    L("}")
    L("")
    L("interface BrainDumpAnalysis {")
    L("  themes: string[];")
    L("  goals: string[];")
    L("  struggles: string[];")
    L("  emotions: string[];")
    L("  archetype: string;")
    L("  priorityFocus: string[];")
    L("}")
    L("")

    # DATA
    L("// -- Data --------------------------------------------------------------------")
    L("")
    L("const FOCUS_AREAS: FocusArea[] = [")
    L("  { id: 'habits', label: 'Build Better Habits', description: 'Create routines that stick', icon: <Flame className=\"w-5 h-5\" />, color: 'from-orange-500 to-amber-500' },")
    L("  { id: 'goals', label: 'Achieve Big Goals', description: 'Break down & conquer goals', icon: <Target className=\"w-5 h-5\" />, color: 'from-blue-500 to-indigo-500' },")
    L("  { id: 'adhd', label: 'Get Organized (ADHD)', description: 'Executive function & focus support', icon: <Brain className=\"w-5 h-5\" />, color: 'from-violet-500 to-purple-500' },")
    L("  { id: 'health', label: 'Health & Fitness', description: 'Move more, feel better', icon: <Dumbbell className=\"w-5 h-5\" />, color: 'from-green-500 to-emerald-500' },")
    L("  { id: 'productivity', label: 'Boost Productivity', description: 'Get more done, stress less', icon: <Zap className=\"w-5 h-5\" />, color: 'from-yellow-500 to-orange-500' },")
    L("  { id: 'learning', label: 'Personal Growth', description: 'Learn & grow every day', icon: <BookOpen className=\"w-5 h-5\" />, color: 'from-purple-500 to-violet-500' },")
    L("  { id: 'wellness', label: 'Mental Wellness', description: 'Mindfulness & self-care', icon: <Heart className=\"w-5 h-5\" />, color: 'from-pink-500 to-rose-500' },")
    L("];")
    L("")
    L("const HABIT_TEMPLATES: HabitTemplate[] = [")
    L("  { id: 'morning-routine', name: 'Morning Routine', icon: <Sparkles className=\"w-5 h-5\" />, description: 'Start your day with intention', frequency: 'Daily', focusAreas: ['habits', 'productivity', 'adhd'] },")
    L("  { id: 'exercise-30', name: 'Exercise 30 min', icon: <Dumbbell className=\"w-5 h-5\" />, description: 'Move your body every day', frequency: 'Daily', focusAreas: ['health', 'habits'] },")
    L("  { id: 'read-20', name: 'Read 20 pages', icon: <BookOpen className=\"w-5 h-5\" />, description: 'Build a reading habit', frequency: 'Daily', focusAreas: ['learning', 'habits'] },")
    L("  { id: 'meditate', name: 'Meditate 10 min', icon: <Heart className=\"w-5 h-5\" />, description: 'Find your calm center', frequency: 'Daily', focusAreas: ['wellness', 'habits', 'adhd'] },")
    L("  { id: 'journal', name: 'Daily Journal', icon: <Brain className=\"w-5 h-5\" />, description: 'Reflect and grow', frequency: 'Daily', focusAreas: ['wellness', 'learning', 'adhd'] },")
    L("  { id: 'water-8', name: 'Drink 8 glasses', icon: <Heart className=\"w-5 h-5\" />, description: 'Stay hydrated all day', frequency: 'Daily', focusAreas: ['health', 'habits', 'adhd'] },")
    L("  { id: 'no-phone-bed', name: 'No phone in bed', icon: <Moon className=\"w-5 h-5\" />, description: 'Better sleep starts here', frequency: 'Daily', focusAreas: ['wellness', 'productivity', 'adhd'] },")
    L("  { id: 'learn-new', name: 'Learn something new', icon: <Target className=\"w-5 h-5\" />, description: '15 min of skill building', frequency: 'Daily', focusAreas: ['learning', 'goals'] },")
    L("  { id: 'gratitude', name: 'Gratitude practice', icon: <Star className=\"w-5 h-5\" />, description: 'Write 3 things grateful for', frequency: 'Daily', focusAreas: ['wellness', 'habits', 'adhd'] },")
    L("  { id: 'walk-10k', name: 'Walk 10,000 steps', icon: <Flame className=\"w-5 h-5\" />, description: 'Keep moving through the day', frequency: 'Daily', focusAreas: ['health'] },")
    L("  { id: 'meal-prep', name: 'Eat healthy meals', icon: <Heart className=\"w-5 h-5\" />, description: 'Nourish your body', frequency: 'Daily', focusAreas: ['health'] },")
    L("  { id: 'deep-work', name: 'Deep work session', icon: <Zap className=\"w-5 h-5\" />, description: '90 min focused work block', frequency: 'Weekdays', focusAreas: ['productivity', 'goals', 'adhd'] },")
    L("];")
    L("")
    L("const TIME_OPTIONS = [")
    L("  { id: 'early', label: 'Early Bird', description: '5 - 7 AM', icon: <Flame className=\"w-6 h-6\" /> },")
    L("  { id: 'morning', label: 'Morning Person', description: '7 - 10 AM', icon: <Sparkles className=\"w-6 h-6\" /> },")
    L("  { id: 'afternoon', label: 'Afternoon Riser', description: '12 - 3 PM', icon: <Zap className=\"w-6 h-6\" /> },")
    L("  { id: 'evening', label: 'Night Owl', description: '6 - 10 PM', icon: <Moon className=\"w-6 h-6\" /> },")
    L("];")
    L("")
    L("const GOAL_EXAMPLES = [")
    L("  'Get fit and lose weight',")
    L("  'Launch my own business',")
    L("  'Learn a new language',")
    L("  'Read 24 books this year',")
    L("  'Build a morning routine',")
    L("  'Land my dream job',")
    L("  'Save and invest money',")
    L("  'Run a half marathon',")
    L("];")
    L("")
    L("const DEADLINE_OPTIONS = [")
    L("  { id: '1m', label: '1 month', description: 'Quick win' },")
    L("  { id: '3m', label: '3 months', description: 'Short sprint' },")
    L("  { id: '6m', label: '6 months', description: 'Mid-term push' },")
    L("  { id: '1y', label: '1 year', description: 'Long-game' },")
    L("  { id: 'ongoing', label: 'Ongoing', description: 'Lifestyle change' },")
    L("];")
    L("")
    L("function cn(...classes: (string | boolean | undefined)[]) {")
    L("  return classes.filter(Boolean).join(' ');")
    L("}")
    L("")

    return '\n'.join(lines)

part1 = build_file()
print(f"Part 1 ready: {len(part1)} chars")
print("Building full file...")

# Actually let me just use the chunk approach that was working before
# and fix all the issues at the end with a single re-indentation pass
print("Writing script...")