//
//  SceneDelegate.swift
//  Resurgo
//
//  This file is automatically generated by Capacitor.
//  Manual changes will be preserved between syncs.
//

import UIKit
import Capacitor

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?
    var bridge: CAPBridge?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
        // If using a storyboard, the `window` property is automatically and will be nil.
        // Use a storyboard-based UI navigation model or load a view controller into a UIWindow manually.
        //
        // Important: Use the UIWindowScene instance `scene` when creating a CAPBridge to ensure correct lifecycle behavior.

        guard let windowScene = (scene as? UIWindowScene) else { return }

        window = UIWindow(windowScene: windowScene)
        bridge = CAPBridge(config: buildConfig(), window: window!)
        bridge?.delegate = self

        if let rootViewController = bridge?.createRootViewController() {
            window?.rootViewController = rootViewController
            window?.makeKeyAndVisible()
        }

        // Suppress "Scene configuration contains no windows" warning
        if #available(iOS 13.0, *) {
            windowScene.sizeRestrictions?.minimumSize = CGSize(width: 1, height: 1)
        }
    }

    func sceneDidDisconnect(_ scene: UIScene) {
        // Called as the scene is being released by the system.
        // This occurs shortly after the scene enters the background, or when its session is discarded.
        // Release any resources associated with this scene that can be re-created the next time the scene connects.
    }

    func sceneDidBecomeActive(_ scene: UIScene) {
        // Called when the scene has moved from an inactive state to an active state.
        // Use this method to restart any tasks that were paused (or not yet started) when the scene was inactive.
    }

    func sceneWillResignActive(_ scene: UIScene) {
        // Called when the scene will move from an active state to an inactive state.
        // This may occur due to temporary interruptions (ex. an incoming phone call).
    }

    func sceneWillEnterForeground(_ scene: UIScene) {
        // Called as the scene is transitioning from the background to the foreground.
        // Use this method to undo the changes made on entering the background.
    }

    func sceneDidEnterBackground(_ scene: UIScene) {
        // Called as the scene transitions from the foreground to the background.
        // Use this method to save data, release shared resources, and store enough application-specific information to restore your application to its current state.
    }
}

extension SceneDelegate: CAPBridgeDelegate {
    func bridgeReady(_ bridge: CAPBridge) {
        // Bridge is ready. Plugins can now be used.
    }

    func bridge(_ bridge: CAPBridge, registerPlugin plugin: CAPPlugin, with className: String) {
        // Register custom plugins here if needed
    }
}
